-- 시장 인터뷰 (MARKET_INTERVIEW)
--
-- 확정된 사업안 하나를 트윈에게 보이고 고정 7문항으로 반응을 듣는 정성 조사다.
-- 「패널 트윈 조사」(V11)를 대체하지만 그 테이블은 건드리지 않는다 — 옛 코드가 아직
-- 참조하고 있고, 지우는 것은 이 작업의 범위가 아니다.
--
-- `task_runs.task_type` 은 VARCHAR(50) 이고 CHECK 제약이 없어 enum 값 추가에
-- 마이그레이션이 필요 없다 — 여기서 만드는 것은 도메인 쪽 두 테이블뿐이다.
-- V22 까지가 기존이고 다음 빈 번호가 V23 임을 파일 목록으로 확인했다.

CREATE TABLE market_interview_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    task_run_id VARCHAR(64) NOT NULL,
    input_snapshot_hash VARCHAR(71) NOT NULL,
    -- 정성 조사에서 n 은 결과를 읽는 단위다. 「20명 중 7명」과 「80명 중 7명」은 다른
    -- 이야기이고, 분모가 값과 떨어지면 언급 수는 해석할 수 없는 숫자가 된다.
    sample_size INTEGER NOT NULL,
    state VARCHAR(20) NOT NULL,
    error_code VARCHAR(80),
    completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL,
    CONSTRAINT fk_market_interview_run_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_market_interview_run_task FOREIGN KEY (task_run_id) REFERENCES task_runs(id) ON DELETE NO ACTION,
    CONSTRAINT uk_market_interview_run_task UNIQUE (task_run_id),
    CONSTRAINT ck_market_interview_run_state CHECK (state IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED')),
    -- 정성 조사의 표준 표본(8~20)에 맞춘 세 값. 우열 조사의 50/100/300 과 다르다 —
    -- 거기는 1인당 여러 셀이었고 여기는 1인 1셀이다.
    CONSTRAINT ck_market_interview_run_sample_size CHECK (sample_size IN (20, 40, 80))
);

CREATE INDEX idx_market_interview_runs_project ON market_interview_runs(project_id, created_at DESC);

CREATE TABLE market_interview_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    source_run_id BIGINT NOT NULL,
    version_number INTEGER NOT NULL,

    -- 결과는 통째로 둔다. 아래 스칼라는 목록·배지용 사본이고 판정의 근거가 아니다.
    result_json TEXT NOT NULL,

    sample_size INTEGER NOT NULL,
    -- 뽑은 사람과 답한 사람은 다르다. 형식 위반·타임아웃으로 빠진 사람이 있으면
    -- 분모가 sample_size 가 아니라 이 값이다.
    answered_count INTEGER NOT NULL,
    theme_count INTEGER NOT NULL,
    -- 오해한 사람 수. 「컨셉이 나쁘다」가 아니라 「컨셉보드가 안 읽힌다」의 지표다 —
    -- 세어 두지 않으면 설명을 고칠 실행과 제품을 고칠 실행이 목록에서 같아 보인다.
    misunderstood_count INTEGER NOT NULL,
    -- 경계 수. 0 이면 계약이 이미 막았어야 한다 — 그래도 눈으로 본다.
    caveat_count INTEGER NOT NULL,

    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL,
    CONSTRAINT fk_market_interview_version_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE NO ACTION,
    CONSTRAINT fk_market_interview_version_run FOREIGN KEY (source_run_id) REFERENCES market_interview_runs(id) ON DELETE NO ACTION,
    CONSTRAINT uk_market_interview_version_run UNIQUE (source_run_id)
);

CREATE INDEX idx_market_interview_versions_project ON market_interview_versions(project_id, version_number DESC);
